[tools]
node = "latest"
go = "latest"
neovim = "nightly"
lazygit = "latest"
fzf = "latest"
ripgrep = "latest"
fd = "latest"
eza = "latest"
zoxide = "latest"
starship = "latest"
tmux = "latest"
tree-sitter = "latest"
